name = "chapter_3"
description = ""
version = "0.1.0-dev"

authors = ["DD"]
maintainers = ["DD <duggan92652@gmail.com>"]
maintainers-logins = ["duggan9265"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
